### PR TITLE
Fix httputils wrapped target path

### PR DESCRIPTION
**Pull request by achasseux**
Into createWrappedTargetPath() method, when targetPath does not contain the question mark "?",  we have to add it for buildind the query string

### CODE REVIEW

**Comment by korotovsky** [comment]
Hi @achasseux!

Thanks for your PR. Could you please investigate why tests failed?

**Comment by korotovsky** [comment]
@achasseux Please check `3.0.x` branch and if everything works well I'll make a tag

**Comment by achasseux** [comment]
Thanks for the merge. This branch 3.0.x is good for me.
I works with php7.0, but Travis can execute the tests with php 5.6
I don't know if the tests can be executed with php 5.5 because of old Symfony version (a change in ContainerBuilder::findTaggedServiceIds() signature [here](https://github.com/symfony/symfony/commit/388e4b3389f187d31781603534f8bdeb771d6c6f)  ) 

I have finished my improvement.

**Comment by korotovsky** [comment]
Thanks a lot!

**Pull request merged**
